# Generated by Django 4.2.9 on 2024-02-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_userprofile_email_and_more'),
        ('reviews', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(related_name='user_reviews', to='profiles.userprofile'),
        ),
    ]
