# Generated by Django 4.2.9 on 2024-03-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
